# Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

---
ansible_python_interpreter: '/usr/bin/python3'
qi_install_python3_docker_pip_names:
- 'pip'
- 'docker'
nginx_container_username: 'nginx'
ansible_user: 'puser'
use_external_certs: 'false'
application_container_username: 'primero'
build_docker_tag: 'latest'
build_docker_container_registry: ''
primero_repo_branch: 'main'
primero_host: 'primero.mflsp.com'
locale_all: 'en,fr,ar'
nginx_ssl_cert_path: '/etc/letsencrypt/live/primero/fullchain.pem'
nginx_ssl_key_path: '/etc/letsencrypt/live/primero/privkey.pem'
use_lets_encrypt: 'true'
qi_install_docker_daemon_json_content: |
  {
    "log-driver": "journald",
    "userns-remap": "{{ application_container_username }}"
  }
