---
- name: 'set journald to not forward logs to syslog'
  ansible.builtin.lineinfile:
    path: '/etc/systemd/journald.conf'
    line: 'ForwardToSyslog=no'
  become: yes
  notify: 'restart_journald'

- meta: 'flush_handlers'

- name: 'start systemd-journald'
  ansible.builtin.service:
    name: 'systemd-journald'
    enabled: yes
    state: 'started'
  become: yes

- name: 'disbale and stop rsyslog service'
  ansible.builtin.service:
    name: 'rsyslog'
    state: 'stopped'
    enabled: no
  become: yes
