---
qi_install_awscli2_version: '2.0.18'
qi_install_awscli2_file: 'awscli-exe-linux-x86_64-{{ qi_install_awscli2_version }}.zip'
qi_install_awscli2_url: 'https://awscli.amazonaws.com/{{ qi_install_awscli2_file }}'