---
- name: 'Debian :: install AWS SSM Agent'
  ansible.builtin.apt:
    deb: 'https://s3.{{ aws_region }}.amazonaws.com/amazon-ssm-{{ aws_region }}/latest/debian_amd64/amazon-ssm-agent.deb'
  become: yes

- name: 'Debian :: start AWS SSM Agent'
  ansible.builtin.service:
    name: 'amazon-ssm-agent'
    enabled: yes
    state: 'started'
  become: yes
